version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    user: '0'
    ports:
      - 8180:8080
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/ruscalimat-export.json
      - 'keycloak_h2:/opt/keycloak/data/h2'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev --import-realm

  minio:
    image: quay.io/minio/minio:RELEASE.2023-09-04T19-57-37Z
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123
    command: server /data --console-address ":9001"

volumes:
  keycloak_h2:
    driver: local
  minio_data:
    driver: local
