[package]
name = "ruscalimat-backend"
version = "0.1.0"
edition = "2021"
authors = ["schitcrafter", "Keyruu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = { version = "6.0.0", features = ["tokio"] }
async-graphql-poem = "6.0.1"
color-eyre = "0.6.2"
dotenvy = "0.15.7"
poem = "1.3.57"
poem-openapi = { version = "3.0.0", features = ["openapi-explorer"] }
sqlx = { version = "0.7.1", features = ["runtime-tokio", "postgres", "macros", "chrono"] }
testcontainers = "0.14.0"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
