[s3]
url = "http://dockerlaptop:9000/"
bucketname = "ruscalimat"
region = "us-east-1"
access_key = "ROOTNAME"
secret_key = "CHANGEME123"

[auth]
admin_group = "admin"
provider_url = "http://dockerlaptop:8180/realms/ruscalimat"

[auth.pinlogin]
keypath = "./private_key.pem"

[db]
url = "postgres://postgres:postgres@dockerlaptop:5432/ruscalimat"
