port = 8080

[s3]
url = "http://minio:9000/"
bucketname = "ruscalimat"
region = "us-east-1"
accesskey = "minioadmin"
secretkey = "minioadmin"

[auth]
admin_group = "admin"
provider.url = "http://keycloak:8080/realms/ruscalimat"

[auth.pinlogin]
keypath = "./private_key.pem"

[db]
url = "postgres://postgres:postgres@db:5432/ruscalimat"
