port = 8080

[s3]
url = "http://localhost:9000/"
bucketname = "ruscalimat"
region = "us-east-1"
access_key = "minioadmin"
secret_key = "minioadmin"

[auth]
admin_group = "admin"
provider_url = "http://localhost:8180/realms/ruscalimat"

[auth.pinlogin]
keypath = "./private_key.pem"

[db]
url = "postgres://postgres:postgres@localhost:5432/ruscalimat"
